version: '3.4'
services:
  mongo:
    image: mongo:4.2
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" ]
      interval: 15s
      timeout: 25s
      retries: 5
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
